# -*- coding: utf-8 -*-
"""RD.Liu營養換算工具

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oRdWJ0aaMDx7Ge-Sp-kXIx-0Jo5tA-aS

RD.Liu營養換算工具
"""

import tkinter as tk
from tkinter import messagebox as msgbox
#開視窗/標題
Diet= tk.Tk()
Diet.title("RD.Liu食物份數轉換精靈")
#視窗大小設定
Diet.geometry('300x300')
Diet.resizable(0,0)
#背景顏色
Diet.config(bg="#B2EBF2")
"""Diet.attribute("-alpha,1")"""
Diet.iconphoto(True,tk.PhotoImage(file='C:/Users/User/Desktop/123.png'))
menu = tk.Menu(Diet)
Diet.config(menu=menu)
menu2 = tk.Menu(menu,tearoff=0)
menu2.add_command(label='開啟')
menu2.add_command(label='儲存')
menu2.add_command(label='另存')
menu.add_cascade(label='功能',menu=menu2)
menu3 = tk.Menu(menu,tearoff=0)
menu3.add_command(label='營養師：劉仲偉')
menu.add_cascade(label='開發者',menu=menu3)

label1= tk.Label(Diet,text = '請輸入年齡(years)')
label1.pack()
entry1=tk.Entry(Diet,width =20) # 輸入欄位的寬度
entry1.pack()
label2= tk.Label(Diet,text = '請輸入身高(cm)')
label2.pack()
entry2=tk.Entry(Diet,width =20) # 輸入欄位的寬度
entry2.pack()
label3 = tk.Label(Diet,text = '請輸入體重(kg)')
label3.pack()
entry3=tk.Entry(Diet,width =20) # 輸入欄位的寬度
entry3.pack()
label4 = tk.Label(Diet,text = '請輸入性別(A=男、B=女)')
label4.pack()
entry4=tk.Entry(Diet,width =20) # 輸入欄位的寬度
entry4.pack()
label5=tk.Label(Diet,text = '請輸入疾病(A=無、B=心、C=肝、D=腎、E=胰、F=肺)')
label5.pack()
entry5=tk.Entry(Diet,width =20) # 輸入欄位的寬度
entry5.pack()
    
def evCount():    
    Height = int(entry2.get())
    Weight = int(entry3.get())
    Age=int(entry1.get())
    
    Metab_M = 66.5+(13.75*Weight)+(5.003*Height)-(6.755*Age) #男性基礎代謝率公式
    Metab_F = 655+(9.563*Weight)+(1.850*Height )-(4.676*Age) #女性基礎代謝率公式
    Bmi = Weight / (Height/100) ** 2 #BMI公式
    
    def Bmi_disc(): #功能:BMI判定肥胖情形描述        
      if Bmi < 18:strBmi="體重過輕，要增加攝取"
      elif 24 <= Bmi <= 27:strBmi="輕微過重，應考慮減重"
      elif 27 <= Bmi <= 30:strBmi="有肥胖情形，建議減重"
      elif Bmi > 30:strBmi="重度肥胖，需要認真減重"
      else:strBmi="體重剛剛好"
      return strBmi
      
    Carbo = 55 
    Pro = 17 
    Lipid =28
    
    if "A" in entry4.get():
      Kcal = Metab_M
    else:
      Kcal = Metab_F
    Carbo_g = (Kcal * Carbo)/400 ##醣類所需克數: 每克醣類提供400大卡
    Pro_g = (Kcal * Pro)/400 ##蛋白質所需克數:每克蛋白質提供400大卡
    Lipid_g = (Kcal * Lipid)/900 ##脂肪所需克數:每克脂肪提供900大卡
    Condition= entry5.get()
    if "C" in Condition:
        Carbo = 60 
        Pro = 10 
        Lipid = 30
    elif "E" in Condition:
        Carbo = 50 
        Pro = 30 
        Lipid = 20
    elif "B" in Condition:
        Carbo = 50 
        Pro = 30 
        Lipid =20
    elif "F" in Condition:
        Carbo = 40 
        Pro = 20 
        Lipid =40
    elif "D" in Condition:
        Carbo = 60 
        Pro = 20 
        Lipid =20
    else :
        Carbo = 55 #float(input("請輸入醣類百分比"))
        Pro = 17 #float(input("請輸入蛋白質百分比"))
        Lipid =28 #float(input("請輸入脂肪百分比"))          
    #乳品類份數: 
    Milk = Carbo_g /12 #每份乳品類含12克醣類
    if Milk > 2:
        Milk = 2
    Veg=(Carbo_g - Milk*12)/5 #每份蔬菜類含5克醣類
    if Veg > 5:
        Veg = 5
    ##水果類:
    Fru =(Carbo_g - Milk*12 - Veg*5)/15 #每份水果類含15克醣類
    if Fru>2: 
      Fru=2
    #全榖雜糧類份數:
    Gra = (Carbo_g - Milk*12 - Veg*5 - Fru*15)/15 #每份全榖雜糧類含15克醣類
    if Gra>16:
      Gra = 16
    ##豆魚蛋肉類份數:
    Meat = (Pro_g - Milk*8 - Veg*1 -Gra*2)/7 #每份蛋豆魚肉含7克蛋白，每份乳品類含8克蛋白，每分蔬菜類含1克蛋白，每份全榖雜糧含2克蛋白)
    if Meat>8:
      Meat = 8
    ##油脂與堅果種子類:
    Oil =( Lipid_g - Milk*4 - Meat*5)/5 #每份蛋豆魚肉含5克脂肪，每份乳品類含4克脂肪)
    if Oil>5:
        Oil=5
    Msg="您的BMI:"+Bmi_disc()
    Msg=Msg+"\n"+"醣類所需克數:"+ str(int(Carbo_g))+str("g")
    Msg=Msg+"\n"+"蛋白質所需克數:"+ str(int(Pro_g))+str("g")
    Msg=Msg+"\n"+"脂肪所需克數:"+ str(int(Lipid_g))+str("g")
    Msg=Msg+"\n"+"總所需熱量:"+ str(int(Kcal))+str("Kcal")
    Msg=Msg+"\n"+"全榖雜糧類:"+ str(int(Gra))+str("份")
    Msg=Msg+"\n"+"豆魚蛋肉類:"+ str(int(Meat))+str("份")
    Msg=Msg+"\n"+"蔬菜類:"+ str(int(Veg))+str("份")
    Msg=Msg+"\n"+"水果類:"+ str(int(Fru))+str("份")
    Msg=Msg+"\n"+"乳品類:"+ str(int(Milk))+str("份")
    Msg=Msg+"\n"+"油脂與堅果種子類:"+ str(int(Oil))+str("份")
    msgbox.showinfo('轉換結果', Msg)
    #tk.Label(second, text="您的BMI:",Bmi_disc).pack()
    #tk.Label(second, text="醣類所需克數:",Carbo_g).pack()
    #tk.Label(second, text="蛋白質所需克數:",Pro_g).pack()
    #tk.Label(second, text="脂肪所需克數:",Lipid_g).pack()
    #tk.Label(second, text="總所需熱量:",(Sex*Kcal)).pack()
    #tk.Label(second, text="乳品類份數:",Milk).pack()
    #tk.Label(second, text="蔬菜類份數:",Veg).pack()
    #tk.Label(second, text="水果類份數:",Fru).pack()
    #tk.Label(second, text="全榖雜糧類份數:",Gra).pack()
    #tk.Label(second, text="豆魚蛋肉類份數:",Meat).pack()
    #tk.Label(second, text="油脂與堅果種子類份數:",Oil).pack()

btCount=tk.Button(Diet,text="輸入",command=evCount)
btCount.pack()
    
Diet.mainloop()